### ISSUE TITLE
More intuitive 'product_id' or mapping somewhere

### ISSUE THREAD

**Issue by diyahir** [vertex-protocol/vertex-python-sdk#43]
It's unclear where product_id is for each product, something like 'SYMBL/{Market type (perps, spot, etc)}' would be better

**Comment by yruej301** [comment]
You can use this query https://vertex-protocol.github.io/vertex-python-sdk/api-reference.html#vertex_protocol.client.apis.MarketQueryAPI.get_all_product_symbols which maps product ids to symbols

**Comment by diyahir** [comment]
From an API perspective, this is quite bad, ideally you should have the ID be a backend thing you guys handle whereas the API should be easier to get up and running

Say for example I want to get the perp information for SOL, first I need to get every product symbol, parse through everything and then get the information I'm looking for. Please consider making this less painful.

For reference, this is how you would do it on kwenta:
```
kwenta = Kwenta(
    network_id=10,
    provider_rpc="",
    wallet_address="",
    private_key=""
)
marketInfo = kwenta.markets['SOL']
```

here is how to do it on vertex:
```
client = create_vertex_client("mainnet")

symbols = client.market.get_all_product_symbols()
vertexFundingRates = {}
vertexProductIds = {}

for symbol in symbols:
    if 'PERP' in symbol.symbol:
        perp = client.market.get_perp_funding_rate(symbol.product_id)
        # remove '-PERP' from symbol name
        vertexFundingRates[symbol.symbol[:-5]] = float(perp.funding_rate_x18)     
        vertexProductIds[symbol.symbol[:-5]] = symbol.product_id


# save product ids to file if you never want to do this again
with open('productIds.json', 'w') as fp:
    json.dump(vertexProductIds, fp)   
```

**Comment by yruej301** [comment]
Appreciate the feedback! we will continue to improve our API and keep the community updated as we make new changes.

**Comment by yruej301** [comment]
hey @diyahir, we added a new symbols mapping that should be a lot cleaner -- you can access it via `client.context.engine_client.get_symbols`, it hits https://vertex-protocol.gitbook.io/docs/developer-resources/api/core/queries/symbols

**Comment by diyahir** [comment]
Thanks
