### ISSUE TITLE
Closing position wrapper function, more intuitive 

### ISSUE THREAD

**Issue by diyahir** [vertex-protocol/vertex-python-sdk#44]
Nowhere in the docs does it discuss closing out a perps positions.

I've searched through everything, and I recommend either doing a perps-specific sanity workflow example or including it here:

https://github.com/vertex-protocol/vertex-python-sdk/blob/main/sanity/vertex_client.py

for reference, this is how you would do it in kwenta 

```
def closeKwentaPosition(client: Kwenta, symbol):
    smaccount = client.get_sm_accounts()[0]
    txId = client.close_position(symbol, smaccount, execute_now=True)
    print("Closing kwenta position:", txId)
```

**Comment by yruej301** [comment]
Hey @diyahir, the team wants to say that we truly appreciate your feedback so pls keep it coming. We are working diligently on improving our API and this is extremely valuable feedback for us!

**Comment by yruej301** [comment]
hey @diyahir, we added a close position API on v1.1.7 --
- API reference: https://vertex-protocol.github.io/vertex-python-sdk/api-reference.html#vertex_protocol.client.apis.MarketExecuteAPI.close_position
- Example: https://github.com/vertex-protocol/vertex-python-sdk/blob/main/sanity/vertex_client.py#L159
