### ISSUE TITLE
Programatic way of getting subaccount address from address

### ISSUE THREAD

**Issue by diyahir** [vertex-protocol/vertex-python-sdk#50]
There is currently no way to retrieve the full subaccount address associated with one wallet

"0x1232....123" maps to "0x1232....123" + some other stuff, i've just been inspecting element on the vertex site to retrieve it, but that's not great. 

For reference this is how you would do it in Kwenta:
```python
smaccounts = Kwenta.get_sm_accounts()
```

I recommend creating a similar function
```python
client = create_vertex_client("mainnet")
subaccounts = client.get_subaccounts()
```

**Comment by yruej301** [comment]
hey @diyahir, there's currently no way to do this via the API. We will look into implementing this and get back to you when it's available. In the meantime, if need to find out all of your subaccounts you can open a ticket via discord https://discord.gg/wyf44Wy2 and we can look it up for you. The default subaccount is `{your-wallet-address}` + the word `default` encoded in hex (`64656661756c740000000000`)

**Comment by diyahir** [comment]
No need to do the discord workflow, just making the issue for tracking purposes. Thanks!

**Comment by yruej301** [comment]
hey @diyahir, this is now supported on the latest SDK version (`v1.1.9`) via `client.subaccount.get_subaccounts(...)`, it hits the following endpoint https://vertex-protocol.gitbook.io/docs/developer-resources/api/indexer/subaccounts. pls note this is currently only on `testnet` and will be available on `mainnet` after 10:30 pm EST later today.
