### ISSUE TITLE
Add ability to get market info for a given symbol 

### ISSUE THREAD

**Issue by diyahir** [vertex-protocol/vertex-python-sdk#78]
Currently to get things like open interest one has to parse through market.get_all_engine_markets

But if I only want a specific symbol, it's just a lot of overhead (also better for your servers) ;)

**Comment by yruej301** [comment]
hey, you can use [get_tickers](https://vertex-protocol.github.io/vertex-python-sdk/api-reference.html#vertex_protocol.indexer_client.IndexerQueryClient.get_tickers) or [get_perp_contracts_info](https://vertex-protocol.github.io/vertex-python-sdk/api-reference.html#vertex_protocol.indexer_client.IndexerQueryClient.get_perp_contracts_info) -- see some examples in https://github.com/vertex-protocol/vertex-python-sdk/blob/dfd193f23fc928d85230e1cac1f7014575510fa6/sanity/indexer_client.py#L27
