### ISSUE TITLE
spot_leverage in QueryMaxOrderSizeParams cannot be explicitly assign a bool value

### ISSUE THREAD

**Issue by LennyNiu** [vertex-protocol/vertex-python-sdk#84]
I tried to use the QueryMaxOrderSizeParams to call get_max_order_size(), I found that in any way, if I set a value on spot_leverage, the API always raises error; if I remove the spot_leverage, it will works.
```python
params = QueryMaxOrderSizeParams(
            sender=sender,
            product_id=product_id,
            price_x18=to_x18(price),
            direction=direction,
            # only if I remove this line, the API call can succeed, otherwise it fails with below error, regardless of True or False
            spot_leverage=False 
    )
    result = client.context.engine_client.get_max_order_size(params)
```
Traceback (most recent call last):
  File "order_vertex.py", line 303, in <module>
    get_max_order_size(65000, "long", spot_leverage=True)
  File "order_vertex.py", line 113, in get_max_order_size
    result = client.context.engine_client.get_max_order_size(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\vertex_protocol\engine_client\query.py", line 291, in get_max_order_size
    self.query(QueryMaxOrderSizeParams.parse_obj(params)).data, MaxOrderSizeData
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\site-packages\vertex_protocol\engine_client\query.py", line 92, in query
    raise QueryFailedException(res.text)
vertex_protocol.utils.exceptions.QueryFailedException: {"status":"failure","error_code":2040,"error":"The value you entered is not a valid boolean. Please try again with a value of true or false.","request_type":"query_max_order_size"}

**Comment by yruej301** [comment]
hey, this has been fixed
